baseURL: "https://risanb.com/"
title: "Risan Bagja"
theme: "naboo"
googleAnalytics: UA-27136969-15
disqusShortname: risanb
markup:
  highlight:
    style: github
imaging:
  quality: 80
params:
  description: "Hi, my name is Risan Bagja. I write about my experiences, daily life, places Iâ€™ve traveled, things I learned, programming stuff, and other random things."
  images: [/img/risan-og.jpg]
  favicon: "earth-icon.png"
