[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.64.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/posts/*"
  to = "/code/:splat"
  status = 302
  force = true
